//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jering.Markdig.Extensions.FlexiBlocks {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jering.Markdig.Extensions.FlexiBlocks.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; must be in interval {1}..
        /// </summary>
        internal static string ArgumentException_ArgumentMustBeInInterval {
            get {
                return ResourceManager.GetString("ArgumentException_ArgumentMustBeInInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; must be larger than 0..
        /// </summary>
        internal static string ArgumentException_ArgumentMustBeLargerThan0 {
            get {
                return ResourceManager.GetString("ArgumentException_ArgumentMustBeLargerThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be negative..
        /// </summary>
        internal static string ArgumentException_ArgumentMustNotBeNegative {
            get {
                return ResourceManager.GetString("ArgumentException_ArgumentMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base URI must be absolute , received &quot;{0}&quot;..
        /// </summary>
        internal static string ArgumentException_BaseUriMustBeAbsolute {
            get {
                return ResourceManager.GetString("ArgumentException_BaseUriMustBeAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since source &quot;{0}&quot; is not an absolute URI, base URI cannot be null, white space or an empty string..
        /// </summary>
        internal static string ArgumentException_BaseUriMustBeDefinedIfSourceIsNotAnAbsoluteUri {
            get {
                return ResourceManager.GetString("ArgumentException_BaseUriMustBeDefinedIfSourceIsNotAnAbsoluteUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &quot;{0}&quot; cannot be null, white space or an empty string..
        /// </summary>
        internal static string ArgumentException_CannotBeNullWhiteSpaceOrAnEmptyString {
            get {
                return ResourceManager.GetString("ArgumentException_CannotBeNullWhiteSpaceOrAnEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If endLineNumber is not -1, it must be larger than or equal to startLineNumber..
        /// </summary>
        internal static string ArgumentException_EndLineNumberMustNotBeLessThanStartLineNumber {
            get {
                return ResourceManager.GetString("ArgumentException_EndLineNumberMustNotBeLessThanStartLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory to be used for file caching, &quot;{0}&quot; is invalid. Refer to the inner exception for details. .
        /// </summary>
        internal static string ArgumentException_InvalidCacheDirectory {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidCacheDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid end line &quot;{0}&quot;. If end line isn&apos;t -1, it must be greater than or equal to start line, &quot;{1}&quot;..
        /// </summary>
        internal static string ArgumentException_InvalidEndLine {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidEndLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; has the value &quot;{1}&quot;, which is not a valid value for the enum &quot;{2}&quot;..
        /// </summary>
        internal static string ArgumentException_InvalidEnumArgument {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidEnumArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid start line &quot;{0}&quot;. Start line must be greater than 0..
        /// </summary>
        internal static string ArgumentException_InvalidStartLine {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidStartLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid start line number &quot;{0}&quot;. Start line number must be greater than 0..
        /// </summary>
        internal static string ArgumentException_InvalidStartLineNumber {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidStartLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; must be defined..
        /// </summary>
        internal static string ArgumentException_MustBeDefined {
            get {
                return ResourceManager.GetString("ArgumentException_MustBeDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid  URI ..
        /// </summary>
        internal static string ArgumentException_NotAValidUri {
            get {
                return ResourceManager.GetString("ArgumentException_NotAValidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one of &quot;{0}&quot; of &quot;{1}&quot; can be defined..
        /// </summary>
        internal static string ArgumentException_OnlyOneArgumentCanBeDefined {
            get {
                return ResourceManager.GetString("ArgumentException_OnlyOneArgumentCanBeDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  URI  &quot;{0}&quot; has unsupported scheme &quot;{1}&quot;..
        /// </summary>
        internal static string ArgumentException_UriSchemeUnsupported {
            get {
                return ResourceManager.GetString("ArgumentException_UriSchemeUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple attempts retrieve content from &quot;{0}&quot; have failed. Please ensure that the Url is valid and that your network connection is stable. Enable debug level logging and try again for more information on why requests are failing..
        /// </summary>
        internal static string ContentRetrievalException_FailedAfterMultipleAttempts {
            get {
                return ResourceManager.GetString("ContentRetrievalException_FailedAfterMultipleAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the remote Url &quot;{0}&quot; is forbidden..
        /// </summary>
        internal static string ContentRetrievalException_RemoteUriAccessForbidden {
            get {
                return ResourceManager.GetString("ContentRetrievalException_RemoteUriAccessForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote Url &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string ContentRetrievalException_RemoteUriDoesNotExist {
            get {
                return ResourceManager.GetString("ContentRetrievalException_RemoteUriDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to &quot;{0}&quot; failed with status code &quot;{1}&quot; and message &quot;{2}&quot;..
        /// </summary>
        internal static string HttpRequestException_UnsuccessfulRequest {
            get {
                return ResourceManager.GetString("HttpRequestException_UnsuccessfulRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following cycle was found in the includes tree: 
        ///{0}.
        /// </summary>
        internal static string InvalidOperationException_CycleInIncludes {
            get {
                return ResourceManager.GetString("InvalidOperationException_CycleInIncludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexiOptionsBlock &quot;{0}&quot; at line &quot;{1}&quot;, column &quot;{2}, does not immediately precede a block that consumes it..
        /// </summary>
        internal static string InvalidOperationException_FlexiOptionsBlockDoesNotImmediatelyPrecedeConsumingBlock {
            get {
                return ResourceManager.GetString("InvalidOperationException_FlexiOptionsBlockDoesNotImmediatelyPrecedeConsumingBloc" +
                        "k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid clipping, no line contains end line substring &quot;{0}&quot;..
        /// </summary>
        internal static string InvalidOperationException_InvalidClippingNoLineContainsEndLineSubstring {
            get {
                return ResourceManager.GetString("InvalidOperationException_InvalidClippingNoLineContainsEndLineSubstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid clipping, no line contains start line substring &quot;{0}&quot;..
        /// </summary>
        internal static string InvalidOperationException_InvalidClippingNoLineContainsStartLineSubstring {
            get {
                return ResourceManager.GetString("InvalidOperationException_InvalidClippingNoLineContainsStartLineSubstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The highlight line range &quot;{0}&quot; is not a subset of the actual number of lines, &quot;{1}&quot;..
        /// </summary>
        internal static string InvalidOperationException_InvalidHighlightLineRange {
            get {
                return ResourceManager.GetString("InvalidOperationException_InvalidHighlightLineRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line number line range &quot;{0}&quot; is not a subset of the actual number of lines, &quot;{1}&quot;..
        /// </summary>
        internal static string InvalidOperationException_InvalidLineNumberLineRange {
            get {
                return ResourceManager.GetString("InvalidOperationException_InvalidLineNumberLineRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid line number ranges: the line number ranges &quot;{0}&quot; and &quot;{1}&quot; overlap..
        /// </summary>
        internal static string InvalidOperationException_LineNumbersCannotOverlap {
            get {
                return ResourceManager.GetString("InvalidOperationException_LineNumbersCannotOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid line ranges for highlighting: the ranges &quot;{0}&quot; and &quot;{1}&quot; overlap..
        /// </summary>
        internal static string InvalidOperationException_LineRangesForHighlightingCannotOverlap {
            get {
                return ResourceManager.GetString("InvalidOperationException_LineRangesForHighlightingCannotOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse JSON &quot;{0}&quot; at line &quot;{1}&quot;, column &quot;{2}&quot;..
        /// </summary>
        internal static string InvalidOperationException_UnableToParseJson {
            get {
                return ResourceManager.GetString("InvalidOperationException_UnableToParseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused FlexiOptionsBlock &quot;{0}&quot; at line &quot;{1}&quot;, column &quot;{2}&quot;..
        /// </summary>
        internal static string InvalidOperationException_UnusedFlexiOptionsBlock {
            get {
                return ResourceManager.GetString("InvalidOperationException_UnusedFlexiOptionsBlock", resourceCulture);
            }
        }
    }
}
