//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jering.Markdig.Extensions.FlexiBlocks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jering.Markdig.Extensions.FlexiBlocks.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid end line &quot;{0}&quot;. If end line isn&apos;t -1, it must be greater than or equal to start line, &quot;{1}&quot;..
        /// </summary>
        internal static string ArgumentException_InvalidEndLine {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidEndLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid start line &quot;{0}&quot;. Start line must be greater than 0..
        /// </summary>
        internal static string ArgumentException_InvalidStartLine {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidStartLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid start line number &quot;{0}&quot;. Start line number must be greater than 0..
        /// </summary>
        internal static string ArgumentException_InvalidStartLineNumber {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidStartLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexiOptionsBlock &quot;{0}&quot; at line &quot;{1}&quot;, column &quot;{2}, does not immediately precede a block that consumes it..
        /// </summary>
        internal static string InvalidOperationException_FlexiOptionsBlockDoesNotImmediatelyPrecedeConsumingBlock {
            get {
                return ResourceManager.GetString("InvalidOperationException_FlexiOptionsBlockDoesNotImmediatelyPrecedeConsumingBloc" +
                        "k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The highlight line range &quot;{0}&quot; is not a subset of the actual number of lines, &quot;{1}&quot;..
        /// </summary>
        internal static string InvalidOperationException_InvalidHighlightLineRange {
            get {
                return ResourceManager.GetString("InvalidOperationException_InvalidHighlightLineRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line number line range &quot;{0}&quot; is not a subset of the actual number of lines, &quot;{1}&quot;..
        /// </summary>
        internal static string InvalidOperationException_InvalidLineNumberLineRange {
            get {
                return ResourceManager.GetString("InvalidOperationException_InvalidLineNumberLineRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid line number ranges: the line number ranges &quot;{0}&quot; and &quot;{1}&quot; overlap..
        /// </summary>
        internal static string InvalidOperationException_LineNumbersCannotOverlap {
            get {
                return ResourceManager.GetString("InvalidOperationException_LineNumbersCannotOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid line ranges for highlighting: the ranges &quot;{0}&quot; and &quot;{1}&quot; overlap..
        /// </summary>
        internal static string InvalidOperationException_LineRangesForHighlightingCannotOverlap {
            get {
                return ResourceManager.GetString("InvalidOperationException_LineRangesForHighlightingCannotOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse JSON &quot;{0}&quot; at line &quot;{1}&quot;, column &quot;{2}&quot;..
        /// </summary>
        internal static string InvalidOperationException_UnableToParseJson {
            get {
                return ResourceManager.GetString("InvalidOperationException_UnableToParseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused FlexiOptionsBlock &quot;{0}&quot; at line &quot;{1}&quot;, column &quot;{2}&quot;..
        /// </summary>
        internal static string InvalidOperationException_UnusedFlexiOptionsBlock {
            get {
                return ResourceManager.GetString("InvalidOperationException_UnusedFlexiOptionsBlock", resourceCulture);
            }
        }
    }
}
